### ISSUE TITLE
Test suite passing?

### ISSUE THREAD

**Issue by harlow** [square/fdoc#33]
I tried running the specs from master and I'm seeing a little red. Maybe one of my gem versions is incorrect?

```
Failures:

  1) Fdoc::EndpointScaffold#consume_response for succesful responses produces a valid JSON schema for the response
     Failure/Error: JSON::Validator.validate!(subject.response_parameters, response_params).should be_true
     NoMethodError:
       undefined method `each' for "???":String
     # ./spec/fdoc/endpoint_scaffold_spec.rb:223:in `block (4 levels) in <top (required)>'

  2) Fdoc::Endpoint#consume_request complex examples is successful
     Failure/Error: subject { endpoint.consume_request(params) }
     NoMethodError:
       undefined method `each' for false:FalseClass
     # ./lib/fdoc/endpoint.rb:19:in `consume_request'
     # ./spec/fdoc/endpoint_spec.rb:37:in `block (3 levels) in <top (required)>'
     # ./spec/fdoc/endpoint_spec.rb:113:in `block (4 levels) in <top (required)>'

  3) Fdoc::Endpoint#consume_request complex examples with no optional keys is successful
     Failure/Error: subject { endpoint.consume_request(params) }
     NoMethodError:
       undefined method `each' for true:TrueClass
     # ./lib/fdoc/endpoint.rb:19:in `consume_request'
     # ./spec/fdoc/endpoint_spec.rb:37:in `block (3 levels) in <top (required)>'
     # ./spec/fdoc/endpoint_spec.rb:124:in `block (5 levels) in <top (required)>'
```

Let me know if anything jumps out to you here. I'd like to get it green before creating any PRs.
