### ISSUE TITLE
Dynamic keys?

### ISSUE THREAD

**Issue by subdigital** [square/fdoc#54]
I have a json response that includes a couple of objects that serve as lookups for the main response fragment:

Example:

``` json
{
   "books": [
       {
            "id":  12,
            "name": "book1",
            "author_id": 1
       },
       {
            "id": 125,
            "name": "book125",
            "author_id": 4
       }
   ],
   "authors": {
       "1": { ....},
       "4": {.....}
   }
}
```

Instead of `authors` being an array, it's instead an object the author id as the key.  This makes it really easy for clients to parse into their native data structures (Dictionary, Hash, whatever) and do quick lookups when building up the response objects.

The main reason is that there might be a ton of books by the same author and this severely cuts down in the overall response size by eliminating the duplication.

Now when I bring fdoc in, it fails because I don't really have a way to describe this structure.

I'm thinking of something like this:

```
   authors:
          description: A lookup of the authors represented in the book list.
          required: false
          type: object
          properties:
            __id__:
              property_type: dynamic 
              type: object
              properties:
                id:
                  description: the id of the author
                  type: integer
                  example: 24512
```

Here the `__id__` is perhaps a convention that this property is special, and the `property_type` attribute set to `dynamic` could tell the validator to not just treat the attribute at face value.

If this is not currently possible to validate with fdoc, I'd love to know.  Failing that is there a way to ignore an entire fragment (but validate the rest) so that my tests don't fail for these endpoints?
