### ISSUE TITLE
JSON request params not properly parsed.

### ISSUE THREAD

**Issue by chris-baynes** [square/fdoc#7]
Using request specs I'm sending a Content-Type json and encoding the params hash as json before sending the request.

The problem is that fdoc sees the request params as just a string and doesn't look at each property, and gives me the following in the scaffolded fdoc:

``` yaml
requestParameters:
  type: string
  example: !binary |-
    eyJ2YWx1ZSI6NTQuMzYsImlkIjoiQjFsbjJ6OUpIWERZOG5XNyJ9
```

To fix this I am json parsing the params before they are sent to consume_request. This makes sense for us as all requests will be json anyway. Does anyone have any thoughts on how to do this in a more generic way? Perhaps it would help to have access to the content type header when consuming requests?
